Project/Project/Models/UserTasks.cs
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Project.Models
{
    public class UserTasks
    {
        [Key]
        [Column(Order = 1)]
        public int TaskID { get; set; }
        [Key]
        [Column(Order = 2)]
        public int ProjectUserID { get; set; }

        public virtual Tasks Tasks { get; set; }
        public virtual ProjectUsers ProjectUsers { get; set; }
    }
}

Project/Project/Controllers/UserTasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class UserTasksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserTasks
        public async Task<ActionResult> Index()
        {
            var userTasks = db.UserTasks.Include(u => u.ProjectUsers).Include(u => u.Tasks);
            return View(await userTasks.ToListAsync());
        }

        // GET: UserTasks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTasks userTasks = await db.UserTasks.FindAsync(id);
            if (userTasks == null)
            {
                return HttpNotFound();
            }
            return View(userTasks);
        }

        // GET: UserTasks/Create
        public ActionResult Create()
        {
            ViewBag.ProjectUserID = new SelectList(db.ProjectUsers, "ProjectUserID", "ApplicationUserID");
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "ApplicationUserID");
            return View();
        }

        // POST: UserTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "TaskID,ProjectUserID")] UserTasks userTasks)
        {
            if (ModelState.IsValid)
            {
                db.UserTasks.Add(userTasks);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectUserID = new SelectList(db.ProjectUsers, "ProjectUserID", "ApplicationUserID", userTasks.ProjectUserID);
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "ApplicationUserID", userTasks.TaskID);
            return View(userTasks);
        }

        // GET: UserTasks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTasks userTasks = await db.UserTasks.FindAsync(id);
            if (userTasks == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectUserID = new SelectList(db.ProjectUsers, "ProjectUserID", "ApplicationUserID", userTasks.ProjectUserID);
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "ApplicationUserID", userTasks.TaskID);
            return View(userTasks);
        }

        // POST: UserTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "TaskID,ProjectUserID")] UserTasks userTasks)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userTasks).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectUserID = new SelectList(db.ProjectUsers, "ProjectUserID", "ApplicationUserID", userTasks.ProjectUserID);
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "ApplicationUserID", userTasks.TaskID);
            return View(userTasks);
        }

        // GET: UserTasks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTasks userTasks = await db.UserTasks.FindAsync(id);
            if (userTasks == null)
            {
                return HttpNotFound();
            }
            return View(userTasks);
        }

        // POST: UserTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            UserTasks userTasks = await db.UserTasks.FindAsync(id);
            db.UserTasks.Remove(userTasks);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //Assign Users view
        public async Task<ActionResult> AssignUsers(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            //var userTask = new UserTasks();
            var task = db.Tasks.FirstOrDefault(t => t.TaskID == id);            
            if(task == null)
            {
                return HttpNotFound();
            }

            //ViewBag for selecting users to assign
            ViewBag.TaskID = task.TaskID;
            ViewBag.PublicID = task.PublicID;
            ViewBag.TaskDescription = task.TaskDescription;
            ViewBag.ProjectUsers = db.ProjectUsers.Where(p => p.PublicID == task.PublicID && !db.UserTasks.Any(t => t.ProjectUserID == p.ProjectUserID && t.TaskID == task.TaskID)).Include(p => p.User).ToList();
            ViewBag.AssignedUsers = db.UserTasks.Where(p => p.TaskID == task.TaskID).Include(u => u.ProjectUsers.User).ToList();

            return View();

        }

        //Add Users to Task post method
        [HttpPost]
        public async Task<ActionResult> AddUserToTask(int? TaskID, int? []projectUserIDs, int? []assignedUserIDs)
        {
            Tasks task = await db.Tasks.FindAsync(TaskID);
            if(task == null)
            {
                return HttpNotFound();
            }

            if(projectUserIDs != null)
            {
                //Loop through each UserIDs and add to UserTasks table
                foreach (var projectUserID in projectUserIDs)
                {
                    UserTasks userTask = new UserTasks();
                    userTask.TaskID = Convert.ToInt32(TaskID);
                    userTask.ProjectUserID = Convert.ToInt32(projectUserID);

                    //Query for checking if entity exists
                    var userTaskQuery = db.UserTasks.SingleOrDefault(u => u.TaskID == userTask.TaskID && u.ProjectUserID == userTask.ProjectUserID);

                    //Checks if entity exists in UserTasks table and removes it if it does
                    if (userTaskQuery != null)
                    {
                        db.UserTasks.Remove(userTaskQuery);
                    }

                    //Add to database
                    db.UserTasks.Add(userTask);
                    db.SaveChanges();
                }
            }            

            if(assignedUserIDs != null)
            {
                //Loop through each UserID for AssignedUsers array and remove the checked ones
                foreach (var projectUserID in assignedUserIDs)
                {
                    UserTasks userTask = new UserTasks();
                    userTask.TaskID = Convert.ToInt32(TaskID);
                    userTask.ProjectUserID = Convert.ToInt32(projectUserID);

                    //Check if entity exists in UserTasks
                    var assignedUserQuery = db.UserTasks.SingleOrDefault(u => u.TaskID == userTask.TaskID && u.ProjectUserID == userTask.ProjectUserID);

                    if (assignedUserQuery != null)
                    {
                        db.UserTasks.Remove(assignedUserQuery);
                    }
                    db.SaveChanges();
                }
            }

            string message = "Users Assigned To Task Have Been Modified Successfully!";
            TempData["Message"] = message;
            return RedirectToAction("Tasks", "Projects", new { id = task.PublicID });
        }      

    }
}

Project/Project/Views/UserTasks/AssignUsers.cshtml
@{
    ViewBag.Title = "AssignUsers";
}
<div class="jumbotron bg-primary text-white">
    <div class="container">
        <h1 class="display-4">Assign Users to Task</h1>
        <p class="lead">Add and Remove Users from this Task...</p>
    </div>
</div>

<h2>Assign Users to Task</h2>


@using (Html.BeginForm("AddUserToTask", "UserTasks", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label>@ViewBag.TaskDescription</label>
    <input type="hidden" name="TaskID" value="@ViewBag.TaskID" />

    <h3>Check to add user to task.</h3>
    <ul style="list-style-type: none;">
        @foreach (var projectUser in @ViewBag.ProjectUsers)
        {
            <li><input type="checkbox" name="projectUserIDs" value="@projectUser.ProjectUserID" />@projectUser.User.UserName</li>
        }
    </ul>

    <br />

    <h3>Check to remove user from task.</h3>
    <ul style="list-style-type: none;">
        @foreach (var assigendUser in @ViewBag.AssignedUsers)
        {
            <li><input type="checkbox" name="assignedUserIDs" value="@assigendUser.ProjectUserID" />@assigendUser.ProjectUsers.User.UserName</li>
        }
    </ul>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Save Changes" /> | 
            <a href="@Url.Action("Tasks", "Projects", new { id = ViewBag.PublicID })">Back to Tasks</a>
        </div>
    </div>    
}

Project/Project/Views/UserTasks/Create.cshtml
@model Project.Models.UserTasks

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserTasks</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TaskID, "TaskID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TaskID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TaskID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectUserID, "ProjectUserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectUserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project/Project/Views/UserTasks/Delete.cshtml
@model Project.Models.UserTasks

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserTasks</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectUsers.ApplicationUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectUsers.ApplicationUserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tasks.ApplicationUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tasks.ApplicationUserID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project/Project/Views/UserTasks/Details.cshtml
@model Project.Models.UserTasks

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserTasks</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectUsers.ApplicationUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectUsers.ApplicationUserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tasks.ApplicationUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tasks.ApplicationUserID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project/Project/Views/UserTasks/Edit.cshtml
@model Project.Models.UserTasks

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserTasks</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TaskID)

        @Html.HiddenFor(model => model.ProjectUserID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project/Project/Views/UserTasks/Index.cshtml
@model IEnumerable<Project.Models.UserTasks>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectUsers.ApplicationUserID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tasks.ApplicationUserID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectUsers.ApplicationUserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tasks.ApplicationUserID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>