Project/Project/Models/ProjectUsers.cs
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace Project.Models
{
    public class ProjectUsers
    {
        [Key]
        public virtual int ProjectUserID { get; set; }
        
        [Required]
        public virtual string ApplicationUserID { get; set; }

        [Required]
        public virtual int PublicID { get; set; }

        //True or false for admin status
        public virtual bool IsAdmin { get; set; }

        public virtual ApplicationUser User { get; set; }
        public virtual Projects Projects { get; set; }

        //Collection of roles for users
        //public virtual ICollection<ProjectRoles> ProjectRoles { get; set; }

        //Collection of tasks assigned to user
        public virtual ICollection<UserTasks> UserTasks { get; set; }
    }
}

Project/Project/Models/Projects.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;

namespace Project.Models
{
    public class Projects
    {
        [Key]
        public int PublicID { get; set; }

        [MaxLength(25)]
        [StringLength(25, ErrorMessage = "The {0} must be at least {2} characters long", MinimumLength = 4)]
        [Display(Name = "Project Name")]
        [Required]
        public string ProjectName { get; set; }

        [MaxLength(50)]
        [Required]
        public string ProjectType { get; set; }

        [MaxLength(250)]
        [StringLength(250, ErrorMessage = "The {0} must be at least {2} characters long", MinimumLength = 10)]
        [Display(Name = "Project Description")]
        [Required]
        public string ProjectDescription { get; set; }        
        
        //Name to set for Blob storage container for this Project
        [MaxLength(63)]
        [StringLength(63, ErrorMessage = "The {0} must be at least {2} characters long", MinimumLength = 3)]
        [Display(Name = "Project Container Name")]
        [Required]
        public string ProjectContainerName { get; set; }

        //Define the certain date/time format to use 
        [DataType(DataType.Date), Column(TypeName = "Date"), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DateCreated { get; set; }

        //Reference ApplicationUser_Id from Identity framework
        public string ApplicationUserID { get; set; }
        
        public virtual ApplicationUser ApplicationUser { get; set; }

        //Collection of files on Project
        public virtual ICollection<Files> Files { get; set; }

        //Collection of users on Project
        public virtual ICollection<ProjectUsers> ProjectUsers { get; set; }

        //Collection of User requests on Project
        public virtual ICollection<ProjectUserRequests> ProjectUserRequests { get; set; }

        //Collection of tasks on Project
        public virtual ICollection<Tasks> Tasks { get; set; }
    }

    public class ProjectDBContext : DbContext
    {
        public virtual DbSet<Projects> Projects { get; set; }        
    }
}

Project/Project/Controllers/ProjectUserRequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using Microsoft.AspNet.Identity;

namespace Project.Controllers
{
    public class ProjectUserRequestsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // POST: RequestMembership
        public async Task<ActionResult> RequestMembership(int projectID, string userID)
        {
            if(userID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            if(ModelState.IsValid)
            {
                if(User.Identity.GetUserId() == null)
                {
                    return View("Unauthorised");
                }

                ProjectUserRequests projectUserRequest = new ProjectUserRequests
                {
                    PublicID = projectID,
                    ApplicationUserID = userID
                };
                db.ProjectUserRequests.Add(projectUserRequest);
                await db.SaveChangesAsync();
            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        // POST: ApproveMembership
        public async Task<ActionResult> ApproveMembership(int? requestID)
        {
            if (User.Identity.GetUserId() == null)
            {
                return View("Unauthorised");
            }

            if (requestID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectUserRequests request = await db.ProjectUserRequests.FindAsync(requestID);
            if(request == null)
            {
                return HttpNotFound();
            }

            var projectUsers = await db.ProjectUsers.Where(p => p.PublicID == request.PublicID).ToListAsync();
            if (!projectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId() && p.IsAdmin == true))
            {
                return View("Unauthorised");
            }

            ProjectUsers projectUser = new ProjectUsers
            {
                ApplicationUserID = request.ApplicationUserID,
                PublicID = request.PublicID,
                IsAdmin = false
            };         
           

            db.ProjectUsers.Add(projectUser);

            //Delete the request once the user has been approved
            db.ProjectUserRequests.Remove(request);

            //Save database
            await db.SaveChangesAsync();

            return Redirect(Request.UrlReferrer.ToString());
        }

        // GET: ProjectUserRequests/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectUserRequests projectUserRequests = await db.ProjectUserRequests.FindAsync(id);
            if (projectUserRequests == null)
            {
                return HttpNotFound();
            }
            return View(projectUserRequests);
        }

        // POST: ProjectUserRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ProjectUserRequests projectUserRequests = await db.ProjectUserRequests.FindAsync(id);
            db.ProjectUserRequests.Remove(projectUserRequests);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Project/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using Project.Services;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Web.Services.Description;
using System.ServiceModel.Channels;

namespace Project.Controllers
{
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private IAzureBlobService azureBlobService;

        //Create an instance of AzureBlobService class, to access the interface methods
        public ProjectsController() :this(new AzureBlobService())
        {

        }

        public ProjectsController(IAzureBlobService azureBlobService)
        {
            this.azureBlobService = azureBlobService;
        }
                
        // GET: Projects
        public async Task<ActionResult> Index()
        {

            var currentUserID = User.Identity.GetUserId();

            if(currentUserID == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var projects = db.Projects.Include(p => p.ApplicationUser);

            ViewBag.Message = Convert.ToString(TempData["Message"]);
            return View(await projects.Where(p => p.ApplicationUserID.Equals(currentUserID)).ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = await db.Projects.FindAsync(id);
            if (projects == null)
            {
                return HttpNotFound();
            }
            return View(projects);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            ViewBag.UserID = User.Identity.GetUserId().ToString();
            ViewBag.CurrentDate = DateTime.Today.ToString("dd/MM/yyyy");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PublicID,ProjectName,ProjectType,ProjectDescription,DateCreated,ApplicationUserID,ProjectContainerName")] Projects projects)
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }


            if (ModelState.IsValid)
            {
                db.Projects.Add(projects);
                await db.SaveChangesAsync();

                //Create Azure Blob Container with ProjectContainerName
                string containerName = projects.ProjectContainerName;                

                //Create Container with ProjectContainerName
                await azureBlobService.CreateBlobContainer(containerName);

                //Add the creator to the list of Project Users
                ProjectUsers projectUser = new ProjectUsers
                { 
                    ApplicationUserID = projects.ApplicationUserID,
                    PublicID = projects.PublicID,
                    IsAdmin = true
                };
                db.ProjectUsers.Add(projectUser);
                await db.SaveChangesAsync();

                string message = "Project Created Successfully!";
                TempData["Message"] = message;
                return RedirectToAction("Index");
            }

            ViewBag.UserID = User.Identity.GetUserId().ToString();
            ViewBag.CurrentDate = DateTime.Now.ToString();
            return View(projects);
        }

        // GET: Projects/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = await db.Projects.FindAsync(id);
            if (projects == null)
            {
                return HttpNotFound();
            }
            if(User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", projects.ApplicationUserID);
            ViewBag.DateCreated = db.Projects.Find(id).DateCreated.ToString("dd/MM/yyyy");
            return View(projects);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PublicID,ProjectName,ProjectType,ProjectDescription,DateCreated,ApplicationUserID,ProjectContainerName")] Projects projects)
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }

            if (ModelState.IsValid)
            {
                db.Entry(projects).State = EntityState.Modified;
                await db.SaveChangesAsync();

                string message = "Project Details Have Been Updated Successfully!";
                TempData["Message"] = message;
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", projects.ApplicationUserID);
            return View(projects);
        }

        // GET: Projects/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = await db.Projects.FindAsync(id);

            if (User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }

            if (projects == null)
            {
                return HttpNotFound();
            }
            return View(projects);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            Projects projects = await db.Projects.FindAsync(id);

            if(User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }

            db.Projects.Remove(projects);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // Projects WorkStation Controller
        public async Task<ActionResult> WorkStation(int? id)
        {
            ViewBag.PublicID = id.ToString();           
            ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.CurrentDate = DateTime.Now.ToString("dd/MM/yyyy HH:mm");
            ViewBag.Message = Convert.ToString(TempData["Message"]);
            ViewBag.Error = Convert.ToString(TempData["Error"]);

            Projects project = await db.Projects.FindAsync(id);
            return View(project);
        }

        // POST: FileUploadAsync
        [HttpPost]
        public async Task<ActionResult> UploadFileAsync(ICollection<HttpPostedFileBase> formFiles, string containerName, string publicID, string userID, DateTime currentDate)
        {
            
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var projectUsers = await db.ProjectUsers.Where(p => p.PublicID.ToString() == publicID).ToListAsync();
            if(!projectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                return View("Unauthorised");
            }

            try
            {
                if (formFiles == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }               
                
                //If file type is not supported, throw error message.
                if(formFiles.Any(f => f.ContentType != "video/mp4" && f.ContentType != "video/avi" && f.ContentType != "video/webm" && f.ContentType != "audio/mpeg" && f.ContentType != "audio/ogg" && f.ContentType != "audio/wav" && !f.ContentType.Contains("image")))
                {
                    string error = "Files Selected Not Supported At Current Time. Aborting Upload";
                    TempData["Error"] = error;

                    return Redirect(Request.UrlReferrer.ToString());
                }

Project/Project/Views/Projects/Activity.cshtml
@model Project.Models.Projects
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Activity";
}

<script>


    //Load Google charts
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawPieChart);
    google.charts.setOnLoadCallback(drawBarChart);
    google.charts.setOnLoadCallback(drawLineChart);

    function drawPieChart(result) {

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'User');
        data.addColumn('number', 'Amount Uploaded');

        //Add relevant data to rows
        data.addRows([
                        @foreach(var item in ViewBag.UserList)
                        {

                            @:['@item.UserName', @Model.Files.Where(p => p.ApplicationUser.UserName == item.UserName).Count()],

                        }
                ]);

            var options = {
          title: 'File Upload Amount by Project Members'
        };

        var chart = new google.visualization.PieChart(document.getElementById('pie_chart_div'));
        chart.draw(data, options);
    }

    function drawBarChart(result) {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'File Type');
        data.addColumn('number', 'Amount Uploaded');

        //Add relevant data to rows
        data.addRows([


                ['Video', @Model.Files.Where(p => p.FileType.Contains("video")).Count()],



                ['Audio', @Model.Files.Where(p => p.FileType.Contains("audio")).Count()],



                ['Image', @Model.Files.Where(p => p.FileType.Contains("image")).Count()],


        ]);

        var options = {
            title: 'Types of Files Uploaded'
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('bar_chart_div'));
        chart.draw(data, options);
    }

    function drawLineChart(result) {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Month');
        data.addColumn('number', 'Amount Uploaded');

        //Add relevant data
        data.addRows([
            @foreach(var item in ViewBag.MonthsList)
            {
                @:['@item', @Model.Files.Where(f => f.DateUploaded.ToString("MMMM") == item).Count()],
            }
        ]);

        var options = {
            title: 'Files Uploaded in the Last Six Months'
        };

        var chart = new google.visualization.LineChart(document.getElementById('line_chart_div'));
        chart.draw(data, options);

    }
</script>


<div class="jumbotron bg-primary text-white">
    <div class="container">
        <h1 class="display-4">@Model.ProjectName: Activity</h1>
        <p class="lead">View various charts to determine user activity, and file type upload patterns...</p>
    </div>
</div>

<h2>Activity</h2>

@if (!Model.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()) && User.Identity.GetUserId() != null && !Model.ProjectUserRequests.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
{
    <h2>Request project membership</h2>
    using (Html.BeginForm("RequestMembership", "ProjectUserRequests", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="hidden" value="@Model.PublicID" name="projectID" />
        <input type="hidden" value="@User.Identity.GetUserId()" name="userID" />
        <input type="submit" class="btn btn-success" value="Submit Request" />
        <br />
    }

}
<p class="text-success">@ViewBag.Message</p>
<p class="text-danger">@ViewBag.Error</p>
@if (Model.ProjectUserRequests.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
{
    <h2>Your request has been sent and is currently being verified.</h2>
}

<div class="card text-center">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("WorkStation", "Projects", new { id = Model.PublicID })">Files <span class="fas fa-file"></span> (@Model.Files.Count())</a>
            </li>
            @if (Model.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("MyFiles", "Projects", new { id = Model.PublicID })">My Files <span class="fas fa-file"></span> (@Model.Files.Where(p => p.ApplicationUserID == User.Identity.GetUserId() && p.PublicID == Model.PublicID).Count())</a>
                </li>
            }
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ProjectUsers", "Projects", new { id = Model.PublicID })">Users <span class="fas fa-user"></span> (@Model.ProjectUsers.Count())</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Tasks", "Projects", new { id = Model.PublicID })">Tasks <span class="fas fa-list"></span> (@Model.Tasks.Where(t => t.IsComplete == false && t.PublicID == Model.PublicID).Count())</a>
            </li>
            @if (Model.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("MyTasks", "Projects", new { id = Model.PublicID })">My Tasks <span class="fas fa-list"></span> (@Model.Tasks.Where(t => t.IsComplete == false && t.PublicID == Model.PublicID && t.UserTasks.Any(u => u.ProjectUsers.ApplicationUserID == User.Identity.GetUserId())).Count())</a>
                </li>
            }
            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("Activity", "Projects", new { id = Model.PublicID })">Activity</a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <!--Display Google Charts-->
        <div id="pie_chart_div" style="width: 900px; height: 500px;"></div>

        <div id="bar_chart_div" style="width: 900px; height: 500px;"></div>

        <div id="line_chart_div" style="width: 900px; height: 500px;"></div>

    </div>
</div>

Project/Project/Views/Projects/Animated.cshtml
@model IEnumerable<Project.Models.Projects>

@{
    ViewBag.Title = "Animated";
}

<div class="jumbotron bg-primary text-white">
    <div class="container">
        <h1 class="display-4">Projects: Animated</h1>
        <p class="lead">View all projects within the animation genre...</p>
    </div>
</div>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mt-2 mb-2">
            <div class="card">
                <div class="card-header">
                    @Html.DisplayFor(modelItem => item.ProjectType)
                </div>
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.ProjectName)</h5>
                    <p class="card-text">@Html.DisplayFor(modelItem => item.ProjectDescription)</p>
                    <a href="@Url.Action("Details", "Projects", new { id = item.PublicID })" class="btn btn-primary">
                        View Details
                        <span class="fa fa-eye"></span>
                    </a>
                </div>
                <div class="card-footer">
                    <p>Created by: @item.ApplicationUser.UserName</p>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </div>
            </div>
        </div>
    }
</div>

Project/Project/Views/Projects/AwaitingApproval.cshtml
@model IEnumerable<Project.Models.Projects>

@{
    ViewBag.Title = "AwaitingApproval";
}

<h2>Awaiting Approval</h2>

@if (Model.Count() == 0)
{
    <div class="card text-center">
        <div class="card-body">
            <h1>No membership requests awaiting approval <span class="fas fa-smile"></span></h1>            
        </div>
    </div>
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mt-2 mb-2">
            <div class="card">
                <div class="card-header">
                    @Html.DisplayFor(modelItem => item.ProjectType)
                </div>
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.ProjectName)</h5>
                    <p class="card-text">@Html.DisplayFor(modelItem => item.ProjectDescription)</p>
                    <a href="@Url.Action("Details", "Projects", new { id = item.PublicID })" class="btn btn-primary">
                        View Details
                        <span class="fa fa-eye"></span>
                    </a>
                </div>
                <div class="card-footer">
                    <p>Created by: @item.ApplicationUser.UserName</p>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </div>
            </div>
        </div>
    }
</div>

Project/Project/Views/Projects/Delete.cshtml
@model Project.Models.Projects

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Projects</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a href="@Url.Action("Index", "Projects")">
            Back to List
            <span class="fas fa-undo"></span>
        </a>
    </div>
    }
</div>

Project/Project/Views/Projects/ProjectUsers.cshtml
@model Project.Models.Projects
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "ProjectUsers";
}

<div class="jumbotron bg-primary text-white">
    <div class="container">
        <h1 class="display-4">@Model.ProjectName: Users</h1>
        <p class="lead">View & add users to current project...</p>
    </div>
</div>

<h2>Project Users</h2>
<p class="text-success">@ViewBag.Message</p>
<br />

<p>Project admins are able to manage project members by adding and removing members, approving member requests, and modifying other user's admin privileges.</p>

@if (!Model.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()) && User.Identity.GetUserId() != null && !Model.ProjectUserRequests.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
{
    <h2>Request project membership</h2>
    using (Html.BeginForm("RequestMembership", "ProjectUserRequests", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="hidden" value="@Model.PublicID" name="projectID" />
        <input type="hidden" value="@User.Identity.GetUserId()" name="userID" />
        <input type="submit" class="btn btn-success" value="Submit Request" />
        <br />
    }

}

@if (Model.ProjectUserRequests.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
{
    <h2>Your request has been sent and is currently being verified.</h2>
}

<div class="card text-center">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("WorkStation", "Projects", new { id = Model.PublicID })">Files <span class="fas fa-file"></span> (@Model.Files.Count())</a>
            </li>
            @if (Model.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("MyFiles", "Projects", new { id = Model.PublicID })">My Files <span class="fas fa-file"></span> (@Model.Files.Where(p => p.ApplicationUserID == User.Identity.GetUserId() && p.PublicID == Model.PublicID).Count())</a>
                </li>
            }
            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("ProjectUsers", "Projects", new { id = Model.PublicID })">Users <span class="fas fa-user"></span> (@Model.ProjectUsers.Count())</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Tasks", "Projects", new { id = Model.PublicID })">Tasks <span class="fas fa-list"></span> (@Model.Tasks.Where(t => t.IsComplete == false && t.PublicID == Model.PublicID).Count())</a>
            </li>
            @if (Model.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("MyTasks", "Projects", new { id = Model.PublicID })">My Tasks <span class="fas fa-list"></span> (@Model.Tasks.Where(t => t.IsComplete == false && t.PublicID == Model.PublicID && t.UserTasks.Any(u => u.ProjectUsers.ApplicationUserID == User.Identity.GetUserId())).Count())</a>
                </li>
            }
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Activity", "Projects", new { id = Model.PublicID })">Activity</a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <!--Retrieve Files Partial view to display.-->
        @Html.Partial("../ProjectUsers/_ProjectUsers", Model.ProjectUsers)
    </div>
</div>