Project/Project/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public async Task<ActionResult> Index()
        {
            var comments = db.Comments.Include(c => c.ApplicationUser).Include(c => c.Files);
            return View(await comments.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = await db.Comments.FindAsync(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            return View(comments);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email");
            ViewBag.FileID = new SelectList(db.Files, "FileID", "FileName");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CommentID,Comment,DateCommented,FileID,ApplicationUserID")] Comments comments)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comments);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", comments.ApplicationUserID);
            ViewBag.FileID = new SelectList(db.Files, "FileID", "FileName", comments.FileID);
            return View(comments);
        }

        // GET: Comments/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = await db.Comments.FindAsync(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", comments.ApplicationUserID);
            ViewBag.FileID = new SelectList(db.Files, "FileID", "FileName", comments.FileID);
            return View(comments);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CommentID,Comment,DateCommented,FileID,ApplicationUserID")] Comments comments)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comments).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", comments.ApplicationUserID);
            ViewBag.FileID = new SelectList(db.Files, "FileID", "FileName", comments.FileID);
            return View(comments);
        }

        // GET: Comments/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comments comments = await db.Comments.FindAsync(id);
            if (comments == null)
            {
                return HttpNotFound();
            }
            return View(comments);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Comments comments = await db.Comments.FindAsync(id);
            var fileID = comments.FileID;

            db.Comments.Remove(comments);
            await db.SaveChangesAsync();

            string message = "Comment Deleted Successfully";
            TempData["Message"] = message;
            return RedirectToAction("Details", "Files", new { id = fileID });
        }

        // POST COMMENT
        [HttpPost]
        public async Task<ActionResult> PostComment(string comment, int fileID, string userID)
        {
            try
            {
                if(comment == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var currentDateTime = DateTime.Now.ToString("dd/MM/yyyy HH:mm");

                var newComment = new Comments()
                {
                    Comment = comment,
                    DateCommented = Convert.ToDateTime(currentDateTime),
                    FileID = fileID,
                    ApplicationUserID = userID,
                };
                db.Comments.Add(newComment);
                await db.SaveChangesAsync();

                string message = "Comment Posted Successfully!";
                TempData["Message"] = message;
                return Redirect(Request.UrlReferrer.ToString());
            }
            catch
            {
                return View("Error");
            }
        }

        //EDIT COMMENT
        [HttpPost]
        public async Task<ActionResult> EditComment(string comment, int commentID, int fileID, string userID)
        {
            if(ModelState.IsValid)
            {
                var editComment = db.Comments.FirstOrDefault(c => c.CommentID == commentID);

                //Set new properties
                editComment.Comment = comment;

                //Save changes
                db.Entry(editComment).State = EntityState.Modified;
                db.SaveChanges();

                string message = "Comment Modified Successfully!";
                TempData["Message"] = message;
                return Redirect(Request.UrlReferrer.ToString());
            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Project/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using Project.Services;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Web.Services.Description;
using System.ServiceModel.Channels;

namespace Project.Controllers
{
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private IAzureBlobService azureBlobService;

        //Create an instance of AzureBlobService class, to access the interface methods
        public ProjectsController() :this(new AzureBlobService())
        {

        }

        public ProjectsController(IAzureBlobService azureBlobService)
        {
            this.azureBlobService = azureBlobService;
        }
                
        // GET: Projects
        public async Task<ActionResult> Index()
        {

            var currentUserID = User.Identity.GetUserId();

            if(currentUserID == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var projects = db.Projects.Include(p => p.ApplicationUser);

            ViewBag.Message = Convert.ToString(TempData["Message"]);
            return View(await projects.Where(p => p.ApplicationUserID.Equals(currentUserID)).ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = await db.Projects.FindAsync(id);
            if (projects == null)
            {
                return HttpNotFound();
            }
            return View(projects);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            ViewBag.UserID = User.Identity.GetUserId().ToString();
            ViewBag.CurrentDate = DateTime.Today.ToString("dd/MM/yyyy");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PublicID,ProjectName,ProjectType,ProjectDescription,DateCreated,ApplicationUserID,ProjectContainerName")] Projects projects)
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }


            if (ModelState.IsValid)
            {
                db.Projects.Add(projects);
                await db.SaveChangesAsync();

                //Create Azure Blob Container with ProjectContainerName
                string containerName = projects.ProjectContainerName;                

                //Create Container with ProjectContainerName
                await azureBlobService.CreateBlobContainer(containerName);

                //Add the creator to the list of Project Users
                ProjectUsers projectUser = new ProjectUsers
                { 
                    ApplicationUserID = projects.ApplicationUserID,
                    PublicID = projects.PublicID,
                    IsAdmin = true
                };
                db.ProjectUsers.Add(projectUser);
                await db.SaveChangesAsync();

                string message = "Project Created Successfully!";
                TempData["Message"] = message;
                return RedirectToAction("Index");
            }

            ViewBag.UserID = User.Identity.GetUserId().ToString();
            ViewBag.CurrentDate = DateTime.Now.ToString();
            return View(projects);
        }

        // GET: Projects/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = await db.Projects.FindAsync(id);
            if (projects == null)
            {
                return HttpNotFound();
            }
            if(User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", projects.ApplicationUserID);
            ViewBag.DateCreated = db.Projects.Find(id).DateCreated.ToString("dd/MM/yyyy");
            return View(projects);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PublicID,ProjectName,ProjectType,ProjectDescription,DateCreated,ApplicationUserID,ProjectContainerName")] Projects projects)
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }

            if (ModelState.IsValid)
            {
                db.Entry(projects).State = EntityState.Modified;
                await db.SaveChangesAsync();

                string message = "Project Details Have Been Updated Successfully!";
                TempData["Message"] = message;
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", projects.ApplicationUserID);
            return View(projects);
        }

        // GET: Projects/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = await db.Projects.FindAsync(id);

            if (User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }

            if (projects == null)
            {
                return HttpNotFound();
            }
            return View(projects);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            Projects projects = await db.Projects.FindAsync(id);

            if(User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }

            db.Projects.Remove(projects);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // Projects WorkStation Controller
        public async Task<ActionResult> WorkStation(int? id)
        {
            ViewBag.PublicID = id.ToString();           
            ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.CurrentDate = DateTime.Now.ToString("dd/MM/yyyy HH:mm");
            ViewBag.Message = Convert.ToString(TempData["Message"]);
            ViewBag.Error = Convert.ToString(TempData["Error"]);

            Projects project = await db.Projects.FindAsync(id);
            return View(project);
        }

        // POST: FileUploadAsync
        [HttpPost]
        public async Task<ActionResult> UploadFileAsync(ICollection<HttpPostedFileBase> formFiles, string containerName, string publicID, string userID, DateTime currentDate)
        {
            
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var projectUsers = await db.ProjectUsers.Where(p => p.PublicID.ToString() == publicID).ToListAsync();
            if(!projectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                return View("Unauthorised");
            }

            try
            {
                if (formFiles == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }               
                
                //If file type is not supported, throw error message.
                if(formFiles.Any(f => f.ContentType != "video/mp4" && f.ContentType != "video/avi" && f.ContentType != "video/webm" && f.ContentType != "audio/mpeg" && f.ContentType != "audio/ogg" && f.ContentType != "audio/wav" && !f.ContentType.Contains("image")))
                {
                    string error = "Files Selected Not Supported At Current Time. Aborting Upload";
                    TempData["Error"] = error;

                    return Redirect(Request.UrlReferrer.ToString());
                }

Project/Project/Views/Files/Create.cshtml
@model Project.Models.Files

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Files</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateUploaded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateUploaded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateUploaded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublicID, "PublicID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PublicID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PublicID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUserID, "ApplicationUserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApplicationUserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApplicationUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/Files/Delete.cshtml
@model Project.Models.Files

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Files</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            Project
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Projects.ProjectName)
        </dd>

        <dt>
            Uploaded By
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.UserName)
        </dd>                

        <dt>
            @Html.DisplayNameFor(model => model.FileType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileSize)
        </dd>       

        <dt>
            @Html.DisplayNameFor(model => model.DateUploaded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateUploaded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a href="@Url.Action("WorkStation", "Projects", new { id = Model.PublicID })">Back to Workstation</a>
        </div>
    }
</div>

Project/Project/Views/Files/Details.cshtml
@model Project.Models.Files
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>



<h4>Files</h4>
<hr />
<div class="row">
    <div class="col-md-6 col-sm-12">
        <dl class="dl-horizontal">
            <dt>
                Uploaded By:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ApplicationUser.UserName)
            </dd>

            <dt>
                Project:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Projects.ProjectName)
            </dd>

            <dt>
                File Name:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FileName)
            </dd>

            <dt>
                File Type:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FileType)
            </dd>           

            <dt>
                Date Uploaded:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateUploaded)
            </dd>

        </dl>
    </div>
    <div class="col-md-6 col-sm-12">
        @if (Model.FileType.Contains("image"))
        {
            <img src="@Model.FilePath" class="rounded img-thumbnail" alt="@Model.FileName" height="400" width="400" />
            <br />
            if (Model.Projects.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                <a href="@Url.Action("DownloadFile", "Files", new { id = Model.FileID })" class="btn btn-primary"><span class="fas fa-download"></span>Download</a>
            }
        }
        @if (Model.FileType.Contains("audio"))
        {
            <!--Div container for waveform.js audio player.-->
            <div id="waveform"></div>
            <br />
            <!--Control buttons for audio-->
            <div class="controls">
                <button class="btn btn-primary" onclick="wavesurfer.playPause()">
                    <i class="fas fa-play"></i>
                    Play /
                    <i class="fas fa-pause"></i>
                    Pause
                </button>
            </div>
            <br />

            if (Model.Projects.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                <a href="@Url.Action("DownloadFile", "Files", new { id = Model.FileID })" class="btn btn-primary"><span class="fas fa-download"></span>Download</a>
            }

            <script src="https://unpkg.com/wavesurfer.js"></script>

            <!--Generate Waveform from Audio File-->
            <script>
                var wavesurfer = WaveSurfer.create({
                    container: '#waveform',
                    barWidth: 2,
                    barHeight: 1, // the height of the wave
                    barGap: null, // the optional spacing between bars of the wave, if not provided will be calculated in legacy format
                    responsive: true
                });

                var song = '@Model.FilePath';
                wavesurfer.load(song);
                wavesurfer.on('ready', function () { wavesurfer.play(); });
            </script>
            <!--Generate Waveform from Audio File-->
        }

        @if (Model.FileType.Contains("video"))
        {
            <video id="video-preview"
                   class="video-js"
                   controls
                   preload="auto"
                   width="640"
                   height="264"
                   data-setup="{}">
                <source src="@Model.FilePath" type="@Model.FileType" />
                <p class="vjs-no-js">
                    To view this video please enable JavaScript, and consider upgrading to a
                    web browser that
                    <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                </p>
            </video>
            <br />
            if (Model.Projects.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                <a href="@Url.Action("DownloadFile", "Files", new { id = Model.FileID })" class="btn btn-primary"><span class="fas fa-download"></span>Download</a>
            }

        }
    </div>
</div>

<p>
    <a href="@Url.Action("WorkStation", "Projects", new { id = Model.PublicID })">Back to Workstation</a>
</p>

@if (Model.Projects.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
{
    using (Html.BeginForm("PostComment", "Comments", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="form-group">
            <textarea class="form-control" id="comment" name="comment" rows="5" cols="50" placeholder="Insert Comment here..." required></textarea>
            <input type="hidden" name="fileID" id="fileID" value="@Model.FileID" />
            <input type="hidden" name="userID" id="userID" value="@ViewBag.UserID" />
        </div>

        <input type="submit" value="Post" class="btn btn-primary" />
    }
}
<p class="text-success">@ViewBag.Message</p>

@if (Model.Projects.ProjectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
{
    <!--Display a Files comments in partial view-->
    @Html.Partial("../Comments/_Comments", Model.Comments.OrderByDescending(c => c.DateCommented))
}

Project/Project/Views/Files/Index.cshtml
@model IEnumerable<Project.Models.Files>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Projects.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileSize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FilePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateUploaded)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateModified)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationUser.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Projects.ProjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileSize)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FilePath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateUploaded)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateModified)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.FileID }) |
            @Html.ActionLink("Details", "Details", new { id=item.FileID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.FileID })
        </td>
    </tr>
}

</table>

Project/Project/Views/Files/ReviewSelectedFiles.cshtml
@model IEnumerable<Project.Models.Files>

<script>
    //Give project id value
    var projectID = $('#projectIDHidden').val();
    console.log(projectID);

    $('#projectID').val(projectID);
</script>

<div class="jumbotron bg-primary text-white">
    <div class="container">
        <h1 class="display-4">Selected Project Files</h1>
        <p class="lead">Review the selected files you wish to download.</p>
        <p id="projectID"></p>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Selected Files</h5>
        @foreach(var item in Model)
        {
            <input type="hidden" id="projectIDHidden" value="@item.PublicID" />
        }
        @using (Html.BeginForm("DownloadSelectedFiles", "Files", FormMethod.Post, new { enctype = "multipart/form-data", id = "selectedFilesForm" }))
        {
            foreach (var item in Model)
            {
                <div class="list-group">  
                    <p></p>
                    <input type="text" readonly class="form-control-plaintext" name="downloadFiles[]" value="@item.FileName" />
                </div>
            }
            <input type="hidden" id="projectID" name="projectID" value="@ViewBag.PublicID" />
            <input type="submit" class="btn btn-primary" value="Download Files" />
        }

    </div>
</div>