Project/Project/Models/ProjectUsers.cs
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace Project.Models
{
    public class ProjectUsers
    {
        [Key]
        public virtual int ProjectUserID { get; set; }
        
        [Required]
        public virtual string ApplicationUserID { get; set; }

        [Required]
        public virtual int PublicID { get; set; }

        //True or false for admin status
        public virtual bool IsAdmin { get; set; }

        public virtual ApplicationUser User { get; set; }
        public virtual Projects Projects { get; set; }

        //Collection of roles for users
        //public virtual ICollection<ProjectRoles> ProjectRoles { get; set; }

        //Collection of tasks assigned to user
        public virtual ICollection<UserTasks> UserTasks { get; set; }
    }
}

Project/Project/Controllers/ProjectUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class ProjectUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProjectUsers
        public async Task<ActionResult> Index()
        {
            return View(await db.ProjectUsers.ToListAsync());
        }

        // GET: ProjectUsers/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectUsers projectUsers = await db.ProjectUsers.FindAsync(id);
            if (projectUsers == null)
            {
                return HttpNotFound();
            }
            return View(projectUsers);
        }

        // GET: ProjectUsers/Create
        public ActionResult AddUser(int projectID)
        {
            var projectUsers = db.ProjectUsers.Select(p => p.ApplicationUserID);

            var returnTo = db.Users.Where(u => !projectUsers.Contains(u.Id)).ToList();

            return View(returnTo);
        }

        // POST: ProjectUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ApplicationUserID,PublicID")] ProjectUsers projectUsers)
        {
            if (ModelState.IsValid)
            {
                db.ProjectUsers.Add(projectUsers);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(projectUsers);
        }

        // GET: ProjectUsers/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectUsers projectUsers = await db.ProjectUsers.FindAsync(id);
            if (projectUsers == null)
            {
                return HttpNotFound();
            }
            return View(projectUsers);
        }

        // POST: ProjectUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ApplicationUserID,PublicID")] ProjectUsers projectUsers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projectUsers).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(projectUsers);
        }

        // GET: ProjectUsers/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectUsers projectUsers = await db.ProjectUsers.FindAsync(id);
            if (projectUsers == null)
            {
                return HttpNotFound();
            }
            return View(projectUsers);
        }

        // POST: ProjectUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            ProjectUsers projectUsers = await db.ProjectUsers.FindAsync(id);
            db.ProjectUsers.Remove(projectUsers);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Project/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using Project.Services;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Web.Services.Description;
using System.ServiceModel.Channels;

namespace Project.Controllers
{
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private IAzureBlobService azureBlobService;

        //Create an instance of AzureBlobService class, to access the interface methods
        public ProjectsController() :this(new AzureBlobService())
        {

        }

        public ProjectsController(IAzureBlobService azureBlobService)
        {
            this.azureBlobService = azureBlobService;
        }
                
        // GET: Projects
        public async Task<ActionResult> Index()
        {

            var currentUserID = User.Identity.GetUserId();

            if(currentUserID == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var projects = db.Projects.Include(p => p.ApplicationUser);

            ViewBag.Message = Convert.ToString(TempData["Message"]);
            return View(await projects.Where(p => p.ApplicationUserID.Equals(currentUserID)).ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = await db.Projects.FindAsync(id);
            if (projects == null)
            {
                return HttpNotFound();
            }
            return View(projects);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            ViewBag.UserID = User.Identity.GetUserId().ToString();
            ViewBag.CurrentDate = DateTime.Today.ToString("dd/MM/yyyy");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PublicID,ProjectName,ProjectType,ProjectDescription,DateCreated,ApplicationUserID,ProjectContainerName")] Projects projects)
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }


            if (ModelState.IsValid)
            {
                db.Projects.Add(projects);
                await db.SaveChangesAsync();

                //Create Azure Blob Container with ProjectContainerName
                string containerName = projects.ProjectContainerName;                

                //Create Container with ProjectContainerName
                await azureBlobService.CreateBlobContainer(containerName);

                //Add the creator to the list of Project Users
                ProjectUsers projectUser = new ProjectUsers
                { 
                    ApplicationUserID = projects.ApplicationUserID,
                    PublicID = projects.PublicID,
                    IsAdmin = true
                };
                db.ProjectUsers.Add(projectUser);
                await db.SaveChangesAsync();

                string message = "Project Created Successfully!";
                TempData["Message"] = message;
                return RedirectToAction("Index");
            }

            ViewBag.UserID = User.Identity.GetUserId().ToString();
            ViewBag.CurrentDate = DateTime.Now.ToString();
            return View(projects);
        }

        // GET: Projects/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = await db.Projects.FindAsync(id);
            if (projects == null)
            {
                return HttpNotFound();
            }
            if(User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", projects.ApplicationUserID);
            ViewBag.DateCreated = db.Projects.Find(id).DateCreated.ToString("dd/MM/yyyy");
            return View(projects);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PublicID,ProjectName,ProjectType,ProjectDescription,DateCreated,ApplicationUserID,ProjectContainerName")] Projects projects)
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }

            if (ModelState.IsValid)
            {
                db.Entry(projects).State = EntityState.Modified;
                await db.SaveChangesAsync();

                string message = "Project Details Have Been Updated Successfully!";
                TempData["Message"] = message;
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", projects.ApplicationUserID);
            return View(projects);
        }

        // GET: Projects/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = await db.Projects.FindAsync(id);

            if (User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }

            if (projects == null)
            {
                return HttpNotFound();
            }
            return View(projects);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }

            Projects projects = await db.Projects.FindAsync(id);

            if(User.Identity.GetUserId() != projects.ApplicationUserID)
            {
                return View("Unauthorised");
            }

            db.Projects.Remove(projects);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // Projects WorkStation Controller
        public async Task<ActionResult> WorkStation(int? id)
        {
            ViewBag.PublicID = id.ToString();           
            ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.CurrentDate = DateTime.Now.ToString("dd/MM/yyyy HH:mm");
            ViewBag.Message = Convert.ToString(TempData["Message"]);
            ViewBag.Error = Convert.ToString(TempData["Error"]);

            Projects project = await db.Projects.FindAsync(id);
            return View(project);
        }

        // POST: FileUploadAsync
        [HttpPost]
        public async Task<ActionResult> UploadFileAsync(ICollection<HttpPostedFileBase> formFiles, string containerName, string publicID, string userID, DateTime currentDate)
        {
            
            if(User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var projectUsers = await db.ProjectUsers.Where(p => p.PublicID.ToString() == publicID).ToListAsync();
            if(!projectUsers.Any(p => p.ApplicationUserID == User.Identity.GetUserId()))
            {
                return View("Unauthorised");
            }

            try
            {
                if (formFiles == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }               
                
                //If file type is not supported, throw error message.
                if(formFiles.Any(f => f.ContentType != "video/mp4" && f.ContentType != "video/avi" && f.ContentType != "video/webm" && f.ContentType != "audio/mpeg" && f.ContentType != "audio/ogg" && f.ContentType != "audio/wav" && !f.ContentType.Contains("image")))
                {
                    string error = "Files Selected Not Supported At Current Time. Aborting Upload";
                    TempData["Error"] = error;

                    return Redirect(Request.UrlReferrer.ToString());
                }

Project/Project/Views/ProjectUsers/AddUser.cshtml
@model IEnumerable<Project.Models.ApplicationUser>

@{
    ViewBag.Title = "Create";
}

<h2>Add User</h2>

@foreach (var item in Model)
{
    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mt-2 mb-2">
        <div class="card">
            <div class="card-header">
                @Html.DisplayFor(modelItem => item.UserName)
            </div>
            <div class="card-body">
                
                <a href="@Ajax.ActionLink("AddUserToProject", "ProjectUsers", new { id = item.Id }, new AjaxOptions { HttpMethod = "POST" })" class="btn btn-primary">
                    View Details
                    <span class="fa fa-user"></span>
                </a>                
            </div>            
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/ProjectUsers/Delete.cshtml
@model Project.Models.ProjectUsers

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjectUsers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PublicID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublicID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project/Project/Views/ProjectUsers/Details.cshtml
@model Project.Models.ProjectUsers

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProjectUsers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PublicID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublicID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ApplicationUserID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project/Project/Views/ProjectUsers/Edit.cshtml
@model Project.Models.ProjectUsers

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectUsers</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApplicationUserID)

        <div class="form-group">
            @Html.LabelFor(model => model.PublicID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublicID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublicID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/ProjectUsers/Index.cshtml
@model IEnumerable<Project.Models.ProjectUsers>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PublicID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PublicID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ApplicationUserID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ApplicationUserID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ApplicationUserID })
        </td>
    </tr>
}

</table>

Project/Project/Views/ProjectUsers/_ProjectUsers.cshtml
@model IEnumerable<Project.Models.ProjectUsers>
@using Microsoft.AspNet.Identity

    <p>

        @if (Model.Any(p => p.IsAdmin == true && p.ApplicationUserID == User.Identity.GetUserId()))
        {
            <a href="@Url.Action("AddUser", "Projects", new { id = ViewBag.PublicID })" class="btn btn-success">
                Add New User
                <span class="fa fa-plus" aria-hidden="true"></span>
            </a>

            <a href="@Url.Action("UserRequests", "Projects", new { id = ViewBag.PublicID })" class="btn btn-success">
                Approve User Requests (@Model.Select(u => u.Projects.ProjectUserRequests.Count).FirstOrDefault())
                <span class="fas fa-check" aria-hidden="true"></span>
            </a>
        }
    </p>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Username</th>            
            <th scope="col">Actions</th>
        </tr>
    </thead>
    @foreach(var item in Model)
    {
        <tr>
            <td>
                @if (item.ApplicationUserID == item.Projects.ApplicationUserID)
                {
                    <a href="@Url.Action("ViewContributions", "Projects", new { id = item.ProjectUserID })">@Html.DisplayFor(modelItem => item.User.UserName)</a> <p>(Creator)</p>
                }
                @if (item.IsAdmin == true && item.ApplicationUserID != item.Projects.ApplicationUserID)
                {
                   <a href="@Url.Action("ViewContributions", "Projects", new { id = item.ProjectUserID })">@Html.DisplayFor(modelItem => item.User.UserName)</a> <p>(Admin)</p>
                }
                @if (item.IsAdmin == false)
                {
                    <a href="@Url.Action("ViewContributions", "Projects", new { id = item.ProjectUserID })">@Html.DisplayFor(modelItem => item.User.UserName)</a>
                }
            </td>
            <td>
                <a class="btn btn-primary" href="@Url.Action("ViewContributions", "Projects", new { id = item.ProjectUserID })"><span class="fas fa-eye"></span></a>
                @if (item.ApplicationUserID != item.Projects.ApplicationUserID)
                {
                    if (Model.Any(p => p.IsAdmin == true && p.ApplicationUserID == User.Identity.GetUserId()))
                    {
                        <a class="btn btn-primary" href="@Url.Action("EditUserPrivileges", "Projects", new { id = item.ProjectUserID })"><span class="fas fa-pen"></span></a>
                        <a class="btn btn-danger" href="@Url.Action("RemoveUser", "Projects", new { id = item.ProjectUserID })"><span class="fas fa-trash"></span></a>
                    }
                }
            </td>
        </tr>
    }
</table>